# Site settings
title: Ajay Ramesh
email: ajayramesh.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ajay Ramesh likes building stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ajayramesh.dev@gmail.com" # the base hostname & protocol for your site
twitter_username: carpetfizz
github_username:  carpetfizz

# Build settings
markdown: kramdown
